### ISSUE TITLE
Can the bot run 24/7 with one-time QR code input?

### ISSUE THREAD

**Issue by buildwithmalik** [ashutosh1919/birthday-wisher-whatsapp#1]
Most of the implementations out there need to be manually started by feeding the QR code. It doesn't make sense if on the day of the birthday we need to run the program, it'd be easier to just type the wish. What are your thoughts?

**Comment by ashutosh1919** [comment]
@AbdulMalikDev , the purpose behind this project is to automate the process of wishing birthdays without worrying about anything. If we customise the code to take input of birthday message before sending a wish, the whole point of automation is not fulfilled. But what you told can be done in one way. There can be a function to send a reminder to the owner of the bot one day before any person's birthday asking for personalized wish message. That can be integrated as a future aspect.

**Comment by buildwithmalik** [comment]
Looking forward to read your article :)

**Comment by ashutosh1919** [comment]
@AbdulMalikDev , The article is published and you can find the link on this repository's README. 

Closing this issue as of now. You can reopen it if you think there are still questions.
